import FetchDataPage from './FetchDataPage';
import FormPage from './FormPage';
import HomePage from './HomePage';
import LoginPage from './LoginPage';
import SplashScreen from './SplashScreen';
import ProfilePage from './Profile';
import ReelsPage from './Reels';
import SearchPage from './Search';
import AddPage from './Add';
export {SplashScreen, LoginPage, HomePage, FormPage, FetchDataPage ,SearchPage,ReelsPage,ProfilePage,AddPage};
